const TILES = [
	{ character: "川", count: 61 },
	{ character: "川", count: 61 },
	{ character: "川", count: 61 },
	{ character: "川", count: 61 },
	{ character: "大", count: 41 },
	{ character: "大", count: 41 },
	{ character: "大", count: 41 },
	{ character: "島", count: 39 },
	{ character: "島", count: 39 },
	{ character: "島", count: 39 },
	{ character: "野", count: 38 },
	{ character: "野", count: 38 },
	{ character: "野", count: 38 },
	{ character: "山", count: 38 },
	{ character: "山", count: 38 },
	{ character: "山", count: 38 },
	{ character: "田", count: 37 },
	{ character: "田", count: 37 },
	{ character: "田", count: 37 },
	{ character: "南", count: 30 },
	{ character: "南", count: 30 },
	{ character: "津", count: 31 },
	{ character: "津", count: 31 },
	{ character: "東", count: 27 },
	{ character: "東", count: 27 },
	{ character: "上", count: 25 },
	{ character: "上", count: 25 },
	{ character: "松", count: 23 },
	{ character: "松", count: 23 },
	{ character: "小", count: 23 },
	{ character: "小", count: 23 },
	{ character: "富", count: 22 },
	{ character: "富", count: 22, red: true },
	{ character: "原", count: 21 },
	{ character: "原", count: 21 },
	{ character: "高", count: 22 },
	{ character: "高", count: 22 },
	{ character: "北", count: 19 },
	{ character: "中", count: 18 },
	{ character: "美", count: 17 },
	{ character: "三", count: 17 },
	{ character: "城", count: 16 },
	{ character: "西", count: 16 },
	{ character: "崎", count: 16 },
	{ character: "長", count: 15 },
	{ character: "豊", count: 14, red: true },
	{ character: "佐", count: 14 },
	{ character: "戸", count: 14 },
	{ character: "平", count: 14 },
	{ character: "日", count: 13 },
	{ character: "井", count: 13 },
	{ character: "浜", count: 13 },
	{ character: "岡", count: 13 },
	{ character: "本", count: 12 },
	{ character: "吉", count: 12 },
	{ character: "木", count: 12 },
	{ character: "内", count: 12 },
	{ character: "和", count: 13 },
	{ character: "白", count: 11 },
	{ character: "見", count: 11 },
	{ character: "郷", count: 11 },
	{ character: "江", count: 11 },
	{ character: "新", count: 11 },
	{ character: "宮", count: 11 },
	{ character: "賀", count: 12 },
	{ character: "河", count: 10 },
	{ character: "泉", count: 10 },
	{ character: "士", count: 10 },
	{ character: "古", count: 10 },
	{ character: "越", count: 9 },
	{ character: "国", count: 9 },
	{ character: "坂", count: 9 },
	{ character: "下", count: 9 },
	{ character: "海", count: 9 },
	{ character: "里", count: 9 },
	{ character: "久", count: 9 },
	{ character: "浦", count: 9 },
	{ character: "福", count: 9, red: true },
	{ character: "石", count: 8 },
	{ character: "宇", count: 8 },
	{ character: "知", count: 8 },
	{ character: "玉", count: 8 },
	{ character: "多", count: 8 },
	{ character: "加", count: 8 },
	{ character: "神", count: 8 },
	{ character: "広", count: 8 },
	{ character: "村", count: 8 },
	{ character: "岩", count: 8 },
	{ character: "清", count: 8 },
	{ character: "伊", count: 8 },
	{ character: "庄", count: 8 },
	{ character: "良", count: 7 },
	{ character: "谷", count: 7 },
	{ character: "鹿", count: 7 },
	{ character: "水", count: 7 },
	{ character: "幌", count: 7 },
	{ character: "土", count: 7 },
	{ character: "阿", count: 7 },
	{ character: "根", count: 7 },
	{ character: "前", count: 6 },
	{ character: "部", count: 6 },
	{ character: "生", count: 6 },
	{ character: "波", count: 6 },
	{ character: "府", count: 6 },
	{ character: "沢", count: 6 },
	{ character: "須", count: 6 },
	{ character: "安", count: 6 },
	{ character: "市", count: 6 },
	{ character: "沼", count: 6 },
	{ character: "米", count: 6 },
	{ character: "別", count: 6 },
	{ character: "瀬", count: 5 },
	{ character: "飯", count: 5 },
	{ character: "金", count: 5 },
	{ character: "熊", count: 6 },
	{ character: "横", count: 5 },
	{ character: "立", count: 5 },
	{ character: "都", count: 5 },
	{ character: "屋", count: 5 },
	{ character: "手", count: 5 },
	{ character: "関", count: 5 },
	{ character: "取", count: 5 },
	{ character: "丹", count: 5 },
	{ character: "五", count: 5 },
	{ character: "名", count: 5 },
	{ character: "羽", count: 5 },
	{ character: "子", count: 5 },
	{ character: "会", count: 4 },
	{ character: "阪", count: 4 },
	{ character: "京", count: 4 },
	{ character: "尾", count: 4 },
	{ character: "十", count: 4 },
	{ character: "奈", count: 4 },
	{ character: "八", count: 3 },
	{ character: "倉", count: 3 },
	{ character: "口", count: 3 }
];

const CITIES = [
	{"name": "江別", "category": "市", "pref": "北海道"},
	{"name": "士別", "category": "市", "pref": "北海道"},
	{"name": "北見", "category": "市", "pref": "北海道"},
	{"name": "岩見沢", "category": "市", "pref": "北海道"},
	{"name": "北広島", "category": "市", "pref": "北海道"},
	{"name": "富良野", "category": "市", "pref": "北海道"},
	{"name": "安平", "category": "町", "pref": "北海道"},
	{"name": "羽幌", "category": "町", "pref": "北海道"},
	{"name": "浦河", "category": "町", "pref": "北海道"},
	{"name": "浦幌", "category": "町", "pref": "北海道"},
	{"name": "下川", "category": "町", "pref": "北海道"},
	{"name": "岩内", "category": "町", "pref": "北海道"},
	{"name": "古平", "category": "町", "pref": "北海道"},
	{"name": "広尾", "category": "町", "pref": "北海道"},
	{"name": "士幌", "category": "町", "pref": "北海道"},
	{"name": "鹿部", "category": "町", "pref": "北海道"},
	{"name": "小平", "category": "町", "pref": "北海道"},
	{"name": "松前", "category": "町", "pref": "北海道"},
	{"name": "沼田", "category": "町", "pref": "北海道"},
	{"name": "上川", "category": "町", "pref": "北海道"},
	{"name": "清水", "category": "町", "pref": "北海道"},
	{"name": "清里", "category": "町", "pref": "北海道"},
	{"name": "知内", "category": "町", "pref": "北海道"},
	{"name": "中川", "category": "町", "pref": "北海道"},
	{"name": "長沼", "category": "町", "pref": "北海道"},
	{"name": "津別", "category": "町", "pref": "北海道"},
	{"name": "東川", "category": "町", "pref": "北海道"},
	{"name": "南幌", "category": "町", "pref": "北海道"},
	{"name": "日高", "category": "町", "pref": "北海道"},
	{"name": "美幌", "category": "町", "pref": "北海道"},
	{"name": "浜中", "category": "町", "pref": "北海道"},
	{"name": "福島", "category": "町", "pref": "北海道"},
	{"name": "平取", "category": "町", "pref": "北海道"},
	{"name": "別海", "category": "町", "pref": "北海道"},
	{"name": "豊浦", "category": "町", "pref": "北海道"},
	{"name": "豊富", "category": "町", "pref": "北海道"},
	{"name": "本別", "category": "町", "pref": "北海道"},
	{"name": "奈井江", "category": "町", "pref": "北海道"},
	{"name": "小清水", "category": "町", "pref": "北海道"},
	{"name": "幌加内", "category": "町", "pref": "北海道"},
	{"name": "木古内", "category": "町", "pref": "北海道"},
	{"name": "上士幌", "category": "町", "pref": "北海道"},
	{"name": "新十津川", "category": "町", "pref": "北海道"},
	{"name": "上富良野", "category": "町", "pref": "北海道"},
	{"name": "中富良野", "category": "町", "pref": "北海道"},
	{"name": "南富良野", "category": "町", "pref": "北海道"},
	{"name": "三沢", "category": "市", "pref": "青森県"},
	{"name": "八戸", "category": "市", "pref": "青森県"},
	{"name": "平川", "category": "市", "pref": "青森県"},
	{"name": "十和田", "category": "市", "pref": "青森県"},
	{"name": "横浜", "category": "町", "pref": "青森県"},
	{"name": "五戸", "category": "町", "pref": "青森県"},
	{"name": "三戸", "category": "町", "pref": "青森県"},
	{"name": "田子", "category": "町", "pref": "青森県"},
	{"name": "東北", "category": "町", "pref": "青森県"},
	{"name": "南部", "category": "町", "pref": "青森県"},
	{"name": "平内", "category": "町", "pref": "青森県"},
	{"name": "佐井", "category": "村", "pref": "青森県"},
	{"name": "新郷", "category": "村", "pref": "青森県"},
	{"name": "宮古", "category": "市", "pref": "岩手県"},
	{"name": "北上", "category": "市", "pref": "岩手県"},
	{"name": "岩手", "category": "町", "pref": "岩手県"},
	{"name": "岩泉", "category": "町", "pref": "岩手県"},
	{"name": "山田", "category": "町", "pref": "岩手県"},
	{"name": "平泉", "category": "町", "pref": "岩手県"},
	{"name": "西和賀", "category": "町", "pref": "岩手県"},
	{"name": "野田", "category": "村", "pref": "岩手県"},
	{"name": "岩沼", "category": "市", "pref": "宮城県"},
	{"name": "大崎", "category": "市", "pref": "宮城県"},
	{"name": "白石", "category": "市", "pref": "宮城県"},
	{"name": "富谷", "category": "市", "pref": "宮城県"},
	{"name": "名取", "category": "市", "pref": "宮城県"},
	{"name": "多賀城", "category": "市", "pref": "宮城県"},
	{"name": "東松島", "category": "市", "pref": "宮城県"},
	{"name": "加美", "category": "町", "pref": "宮城県"},
	{"name": "松島", "category": "町", "pref": "宮城県"},
	{"name": "川崎", "category": "町", "pref": "宮城県"},
	{"name": "村田", "category": "町", "pref": "宮城県"},
	{"name": "大郷", "category": "町", "pref": "宮城県"},
	{"name": "大和", "category": "町", "pref": "宮城県"},
	{"name": "美里", "category": "町", "pref": "宮城県"},
	{"name": "大河原", "category": "町", "pref": "宮城県"},
	{"name": "横手", "category": "市", "pref": "秋田県"},
	{"name": "井川", "category": "町", "pref": "秋田県"},
	{"name": "小坂", "category": "町", "pref": "秋田県"},
	{"name": "美郷", "category": "町", "pref": "秋田県"},
	{"name": "上山", "category": "市", "pref": "山形県"},
	{"name": "新庄", "category": "市", "pref": "山形県"},
	{"name": "村山", "category": "市", "pref": "山形県"},
	{"name": "長井", "category": "市", "pref": "山形県"},
	{"name": "東根", "category": "市", "pref": "山形県"},
	{"name": "米沢", "category": "市", "pref": "山形県"},
	{"name": "河北", "category": "町", "pref": "山形県"},
	{"name": "金山", "category": "町", "pref": "山形県"},
	{"name": "三川", "category": "町", "pref": "山形県"},
	{"name": "小国", "category": "町", "pref": "山形県"},
	{"name": "庄内", "category": "町", "pref": "山形県"},
	{"name": "西川", "category": "町", "pref": "山形県"},
	{"name": "川西", "category": "町", "pref": "山形県"},
	{"name": "大江", "category": "町", "pref": "山形県"},
	{"name": "中山", "category": "町", "pref": "山形県"},
	{"name": "飯豊", "category": "町", "pref": "山形県"},
	{"name": "大石田", "category": "町", "pref": "山形県"},
	{"name": "戸沢", "category": "村", "pref": "山形県"},
	{"name": "福島", "category": "市", "pref": "福島県", "kento":true},
	{"name": "田村", "category": "市", "pref": "福島県"},
	{"name": "白河", "category": "市", "pref": "福島県"},
	{"name": "本宮", "category": "市", "pref": "福島県"},
	{"name": "須賀川", "category": "市", "pref": "福島県"},
	{"name": "大熊", "category": "町", "pref": "福島県"},
	{"name": "下郷", "category": "町", "pref": "福島県"},
	{"name": "金山", "category": "町", "pref": "福島県"},
	{"name": "広野", "category": "町", "pref": "福島県"},
	{"name": "国見", "category": "町", "pref": "福島県"},
	{"name": "三島", "category": "町", "pref": "福島県"},
	{"name": "小野", "category": "町", "pref": "福島県"},
	{"name": "石川", "category": "町", "pref": "福島県"},
	{"name": "富岡", "category": "町", "pref": "福島県"},
	{"name": "西会津", "category": "町", "pref": "福島県"},
	{"name": "南会津", "category": "町", "pref": "福島県"},
	{"name": "会津坂下", "category": "町", "pref": "福島県"},
	{"name": "会津美里", "category": "町", "pref": "福島県"},
	{"name": "玉川", "category": "村", "pref": "福島県"},
	{"name": "西郷", "category": "村", "pref": "福島県"},
	{"name": "川内", "category": "村", "pref": "福島県"},
	{"name": "泉崎", "category": "村", "pref": "福島県"},
	{"name": "大玉", "category": "村", "pref": "福島県"},
	{"name": "中島", "category": "村", "pref": "福島県"},
	{"name": "平田", "category": "村", "pref": "福島県"},
	{"name": "水戸", "category": "市", "pref": "茨城県", "kento":true},
	{"name": "日立", "category": "市", "pref": "茨城県"},
	{"name": "古河", "category": "市", "pref": "茨城県"},
	{"name": "坂東", "category": "市", "pref": "茨城県"},
	{"name": "取手", "category": "市", "pref": "茨城県"},
	{"name": "石岡", "category": "市", "pref": "茨城県"},
	{"name": "土浦", "category": "市", "pref": "茨城県"},
	{"name": "小美玉", "category": "市", "pref": "茨城県"},
	{"name": "阿見", "category": "町", "pref": "茨城県"},
	{"name": "河内", "category": "町", "pref": "茨城県"},
	{"name": "城里", "category": "町", "pref": "茨城県"},
	{"name": "大子", "category": "町", "pref": "茨城県"},
	{"name": "東海", "category": "村", "pref": "茨城県"},
	{"name": "美浦", "category": "村", "pref": "茨城県"},
	{"name": "宇都宮", "category": "市", "pref": "栃木県", "kento":true},
	{"name": "下野", "category": "市", "pref": "栃木県"},
	{"name": "佐野", "category": "市", "pref": "栃木県"},
	{"name": "鹿沼", "category": "市", "pref": "栃木県"},
	{"name": "小山", "category": "市", "pref": "栃木県"},
	{"name": "大田原", "category": "市", "pref": "栃木県"},
	{"name": "野木", "category": "町", "pref": "栃木県"},
	{"name": "上三川", "category": "町", "pref": "栃木県"},
	{"name": "高根沢", "category": "町", "pref": "栃木県"},
	{"name": "安中", "category": "市", "pref": "群馬県"},
	{"name": "高崎", "category": "市", "pref": "群馬県"},
	{"name": "沼田", "category": "市", "pref": "群馬県"},
	{"name": "富岡", "category": "市", "pref": "群馬県"},
	{"name": "吉岡", "category": "町", "pref": "群馬県"},
	{"name": "玉村", "category": "町", "pref": "群馬県"},
	{"name": "大泉", "category": "町", "pref": "群馬県"},
	{"name": "長野原", "category": "町", "pref": "群馬県"},
	{"name": "高山", "category": "村", "pref": "群馬県"},
	{"name": "上野", "category": "村", "pref": "群馬県"},
	{"name": "川口", "category": "市", "pref": "埼玉県"},
	{"name": "熊谷", "category": "市", "pref": "埼玉県"},
	{"name": "羽生", "category": "市", "pref": "埼玉県"},
	{"name": "越谷", "category": "市", "pref": "埼玉県"},
	{"name": "加須", "category": "市", "pref": "埼玉県"},
	{"name": "吉川", "category": "市", "pref": "埼玉県"},
	{"name": "戸田", "category": "市", "pref": "埼玉県"},
	{"name": "坂戸", "category": "市", "pref": "埼玉県"},
	{"name": "三郷", "category": "市", "pref": "埼玉県"},
	{"name": "上尾", "category": "市", "pref": "埼玉県"},
	{"name": "川越", "category": "市", "pref": "埼玉県"},
	{"name": "日高", "category": "市", "pref": "埼玉県"},
	{"name": "白岡", "category": "市", "pref": "埼玉県"},
	{"name": "北本", "category": "市", "pref": "埼玉県"},
	{"name": "本庄", "category": "市", "pref": "埼玉県"},
	{"name": "富士見", "category": "市", "pref": "埼玉県"},
	{"name": "東松山", "category": "市", "pref": "埼玉県"},
	{"name": "横瀬", "category": "町", "pref": "埼玉県"},
	{"name": "伊奈", "category": "町", "pref": "埼玉県"},
	{"name": "越生", "category": "町", "pref": "埼玉県"},
	{"name": "吉見", "category": "町", "pref": "埼玉県"},
	{"name": "小川", "category": "町", "pref": "埼玉県"},
	{"name": "上里", "category": "町", "pref": "埼玉県"},
	{"name": "神川", "category": "町", "pref": "埼玉県"},
	{"name": "川島", "category": "町", "pref": "埼玉県"},
	{"name": "美里", "category": "町", "pref": "埼玉県"},
	{"name": "小鹿野", "category": "町", "pref": "埼玉県"},
	{"name": "浦安", "category": "市", "pref": "千葉県"},
	{"name": "佐倉", "category": "市", "pref": "千葉県"},
	{"name": "市原", "category": "市", "pref": "千葉県"},
	{"name": "市川", "category": "市", "pref": "千葉県"},
	{"name": "松戸", "category": "市", "pref": "千葉県"},
	{"name": "東金", "category": "市", "pref": "千葉県"},
	{"name": "白井", "category": "市", "pref": "千葉県"},
	{"name": "富津", "category": "市", "pref": "千葉県"},
	{"name": "富里", "category": "市", "pref": "千葉県"},
	{"name": "野田", "category": "市", "pref": "千葉県"},
	{"name": "神崎", "category": "町", "pref": "千葉県"},
	{"name": "多古", "category": "町", "pref": "千葉県"},
	{"name": "長南", "category": "町", "pref": "千葉県"},
	{"name": "東庄", "category": "町", "pref": "千葉県"},
	{"name": "白子", "category": "町", "pref": "千葉県"},
	{"name": "長生", "category": "村", "pref": "千葉県"},
	{"name": "国立", "category": "市", "pref": "東京都"},
	{"name": "立川", "category": "市", "pref": "東京都"},
	{"name": "羽村", "category": "市", "pref": "東京都"},
	{"name": "小平", "category": "市", "pref": "東京都"},
	{"name": "清瀬", "category": "市", "pref": "東京都"},
	{"name": "日野", "category": "市", "pref": "東京都"},
	{"name": "府中", "category": "市", "pref": "東京都"},
	{"name": "福生", "category": "市", "pref": "東京都"},
	{"name": "小金井", "category": "市", "pref": "東京都"},
	{"name": "西東京", "category": "市", "pref": "東京都"},
	{"name": "東村山", "category": "市", "pref": "東京都"},
	{"name": "東大和", "category": "市", "pref": "東京都"},
	{"name": "大島", "category": "町", "pref": "東京都", "ritou":true},
	{"name": "新島", "category": "村", "pref": "東京都", "ritou":true},
	{"name": "神津島", "category": "村", "pref": "東京都", "ritou":true},
	{"name": "横浜", "category": "市", "pref": "神奈川県", "seirei":true, "kento":true},
	{"name": "川崎", "category": "市", "pref": "神奈川県", "seirei":true},
	{"name": "三浦", "category": "市", "pref": "神奈川県"},
	{"name": "大和", "category": "市", "pref": "神奈川県"},
	{"name": "横須賀", "category": "市", "pref": "神奈川県"},
	{"name": "小田原", "category": "市", "pref": "神奈川県"},
	{"name": "山北", "category": "町", "pref": "神奈川県"},
	{"name": "松田", "category": "町", "pref": "神奈川県"},
	{"name": "大井", "category": "町", "pref": "神奈川県"},
	{"name": "中井", "category": "町", "pref": "神奈川県"},
	{"name": "清川", "category": "村", "pref": "神奈川県"},
	{"name": "五泉", "category": "市", "pref": "新潟県"},
	{"name": "上越", "category": "市", "pref": "新潟県"},
	{"name": "村上", "category": "市", "pref": "新潟県"},
	{"name": "長岡", "category": "市", "pref": "新潟県"},
	{"name": "阿賀野", "category": "市", "pref": "新潟県"},
	{"name": "阿賀", "category": "町", "pref": "新潟県"},
	{"name": "津南", "category": "町", "pref": "新潟県"},
	{"name": "田上", "category": "町", "pref": "新潟県"},
	{"name": "関川", "category": "村", "pref": "新潟県"},
	{"name": "富山", "category": "市", "pref": "富山県", "kento":true},
	{"name": "高岡", "category": "市", "pref": "富山県"},
	{"name": "立山", "category": "町", "pref": "富山県"},
	{"name": "上市", "category": "町", "pref": "富山県"},
	{"name": "金沢", "category": "市", "pref": "石川県", "kento":true},
	{"name": "加賀", "category": "市", "pref": "石川県"},
	{"name": "小松", "category": "市", "pref": "石川県"},
	{"name": "白山", "category": "市", "pref": "石川県"},
	{"name": "川北", "category": "町", "pref": "石川県"},
	{"name": "福井", "category": "市", "pref": "福井県", "kento":true},
	{"name": "越前", "category": "市", "pref": "福井県"},
	{"name": "坂井", "category": "市", "pref": "福井県"},
	{"name": "小浜", "category": "市", "pref": "福井県"},
	{"name": "大野", "category": "市", "pref": "福井県"},
	{"name": "越前", "category": "町", "pref": "福井県"},
	{"name": "高浜", "category": "町", "pref": "福井県"},
	{"name": "美浜", "category": "町", "pref": "福井県"},
	{"name": "南越前", "category": "町", "pref": "福井県"},
	{"name": "上野原", "category": "市", "pref": "山梨県"},
	{"name": "富士吉田", "category": "市", "pref": "山梨県"},
	{"name": "南部", "category": "町", "pref": "山梨県"},
	{"name": "富士川", "category": "町", "pref": "山梨県"},
	{"name": "市川三郷", "category": "町", "pref": "山梨県"},
	{"name": "丹波山", "category": "村", "pref": "山梨県"},
	{"name": "長野", "category": "市", "pref": "長野県", "kento":true},
	{"name": "岡谷", "category": "市", "pref": "長野県"},
	{"name": "佐久", "category": "市", "pref": "長野県"},
	{"name": "松本", "category": "市", "pref": "長野県"},
	{"name": "上田", "category": "市", "pref": "長野県"},
	{"name": "須坂", "category": "市", "pref": "長野県"},
	{"name": "中野", "category": "市", "pref": "長野県"},
	{"name": "飯山", "category": "市", "pref": "長野県"},
	{"name": "飯田", "category": "市", "pref": "長野県"},
	{"name": "阿南", "category": "町", "pref": "長野県"},
	{"name": "坂城", "category": "町", "pref": "長野県"},
	{"name": "小海", "category": "町", "pref": "長野県"},
	{"name": "松川", "category": "町", "pref": "長野県"},
	{"name": "上松", "category": "町", "pref": "長野県"},
	{"name": "長和", "category": "町", "pref": "長野県"},
	{"name": "飯島", "category": "町", "pref": "長野県"},
	{"name": "富士見", "category": "町", "pref": "長野県"},
	{"name": "原", "category": "村", "pref": "長野県"},
	{"name": "宮田", "category": "村", "pref": "長野県"},
	{"name": "高山", "category": "村", "pref": "長野県"},
	{"name": "根羽", "category": "村", "pref": "長野県"},
	{"name": "小川", "category": "村", "pref": "長野県"},
	{"name": "小谷", "category": "村", "pref": "長野県"},
	{"name": "松川", "category": "村", "pref": "長野県"},
	{"name": "生坂", "category": "村", "pref": "長野県"},
	{"name": "川上", "category": "村", "pref": "長野県"},
	{"name": "大鹿", "category": "村", "pref": "長野県"},
	{"name": "中川", "category": "村", "pref": "長野県"},
	{"name": "平谷", "category": "村", "pref": "長野県"},
	{"name": "木島平", "category": "村", "pref": "長野県"},
	{"name": "関", "category": "市", "pref": "岐阜県"},
	{"name": "羽島", "category": "市", "pref": "岐阜県"},
	{"name": "海津", "category": "市", "pref": "岐阜県"},
	{"name": "高山", "category": "市", "pref": "岐阜県"},
	{"name": "中津川", "category": "市", "pref": "岐阜県"},
	{"name": "安八", "category": "町", "pref": "岐阜県"},
	{"name": "神戸", "category": "町", "pref": "岐阜県"},
	{"name": "大野", "category": "町", "pref": "岐阜県"},
	{"name": "白川", "category": "町", "pref": "岐阜県"},
	{"name": "富加", "category": "町", "pref": "岐阜県"},
	{"name": "白川", "category": "村", "pref": "岐阜県"},
	{"name": "東白川", "category": "村", "pref": "岐阜県"},
	{"name": "浜松", "category": "市", "pref": "静岡県", "seirei":true},
	{"name": "伊東", "category": "市", "pref": "静岡県"},
	{"name": "下田", "category": "市", "pref": "静岡県"},
	{"name": "三島", "category": "市", "pref": "静岡県"},
	{"name": "沼津", "category": "市", "pref": "静岡県"},
	{"name": "島田", "category": "市", "pref": "静岡県"},
	{"name": "富士", "category": "市", "pref": "静岡県"},
	{"name": "富士宮", "category": "市", "pref": "静岡県"},
	{"name": "河津", "category": "町", "pref": "静岡県"},
	{"name": "吉田", "category": "町", "pref": "静岡県"},
	{"name": "小山", "category": "町", "pref": "静岡県"},
	{"name": "松崎", "category": "町", "pref": "静岡県"},
	{"name": "清水", "category": "町", "pref": "静岡県"},
	{"name": "長泉", "category": "町", "pref": "静岡県"},
	{"name": "川根本", "category": "町", "pref": "静岡県"},
	{"name": "名古屋", "category": "市", "pref": "愛知県", "seirei":true, "kento":true},
	{"name": "知立", "category": "市", "pref": "愛知県"},
	{"name": "安城", "category": "市", "pref": "愛知県"},
	{"name": "岡崎", "category": "市", "pref": "愛知県"},
	{"name": "岩倉", "category": "市", "pref": "愛知県"},
	{"name": "江南", "category": "市", "pref": "愛知県"},
	{"name": "高浜", "category": "市", "pref": "愛知県"},
	{"name": "新城", "category": "市", "pref": "愛知県"},
	{"name": "瀬戸", "category": "市", "pref": "愛知県"},
	{"name": "清須", "category": "市", "pref": "愛知県"},
	{"name": "西尾", "category": "市", "pref": "愛知県"},
	{"name": "大府", "category": "市", "pref": "愛知県"},
	{"name": "知多", "category": "市", "pref": "愛知県"},
	{"name": "津島", "category": "市", "pref": "愛知県"},
	{"name": "田原", "category": "市", "pref": "愛知県"},
	{"name": "東海", "category": "市", "pref": "愛知県"},
	{"name": "豊川", "category": "市", "pref": "愛知県"},
	{"name": "豊田", "category": "市", "pref": "愛知県"},
	{"name": "長久手", "category": "市", "pref": "愛知県"},
	{"name": "北名古屋", "category": "市", "pref": "愛知県"},
	{"name": "大口", "category": "町", "pref": "愛知県"},
	{"name": "東浦", "category": "町", "pref": "愛知県"},
	{"name": "東郷", "category": "町", "pref": "愛知県"},
	{"name": "美浜", "category": "町", "pref": "愛知県"},
	{"name": "豊山", "category": "町", "pref": "愛知県"},
	{"name": "南知多", "category": "町", "pref": "愛知県"},
	{"name": "豊根", "category": "村", "pref": "愛知県"},
	{"name": "津", "category": "市", "pref": "三重県", "kento":true},
	{"name": "熊野", "category": "市", "pref": "三重県"},
	{"name": "松阪", "category": "市", "pref": "三重県"},
	{"name": "伊賀", "category": "市", "pref": "三重県"},
	{"name": "玉城", "category": "町", "pref": "三重県"},
	{"name": "川越", "category": "町", "pref": "三重県"},
	{"name": "大津", "category": "市", "pref": "滋賀県", "kento":true},
	{"name": "高島", "category": "市", "pref": "滋賀県"},
	{"name": "長浜", "category": "市", "pref": "滋賀県"},
	{"name": "米原", "category": "市", "pref": "滋賀県"},
	{"name": "多賀", "category": "町", "pref": "滋賀県"},
	{"name": "日野", "category": "町", "pref": "滋賀県"},
	{"name": "豊郷", "category": "町", "pref": "滋賀県"},
	{"name": "京都", "category": "市", "pref": "京都府", "seirei":true, "kento":true},
	{"name": "宮津", "category": "市", "pref": "京都府"},
	{"name": "南丹", "category": "市", "pref": "京都府"},
	{"name": "木津川", "category": "市", "pref": "京都府"},
	{"name": "長岡京", "category": "市", "pref": "京都府"},
	{"name": "福知山", "category": "市", "pref": "京都府"},
	{"name": "伊根", "category": "町", "pref": "京都府"},
	{"name": "井手", "category": "町", "pref": "京都府"},
	{"name": "大山崎", "category": "町", "pref": "京都府"},
	{"name": "京丹波", "category": "町", "pref": "京都府"},
	{"name": "南山城", "category": "村", "pref": "京都府"},
	{"name": "大阪", "category": "市", "pref": "大阪府", "seirei":true, "kento":true},
	{"name": "阪南", "category": "市", "pref": "大阪府"},
	{"name": "高石", "category": "市", "pref": "大阪府"},
	{"name": "松原", "category": "市", "pref": "大阪府"},
	{"name": "泉南", "category": "市", "pref": "大阪府"},
	{"name": "大東", "category": "市", "pref": "大阪府"},
	{"name": "八尾", "category": "市", "pref": "大阪府"},
	{"name": "豊中", "category": "市", "pref": "大阪府"},
	{"name": "和泉", "category": "市", "pref": "大阪府"},
	{"name": "東大阪", "category": "市", "pref": "大阪府"},
	{"name": "泉大津", "category": "市", "pref": "大阪府"},
	{"name": "泉佐野", "category": "市", "pref": "大阪府"},
	{"name": "河内長野", "category": "市", "pref": "大阪府"},
	{"name": "熊取", "category": "町", "pref": "大阪府"},
	{"name": "河南", "category": "町", "pref": "大阪府"},
	{"name": "島本", "category": "町", "pref": "大阪府"},
	{"name": "神戸", "category": "市", "pref": "兵庫県", "seirei":true, "kento":true},
	{"name": "伊丹", "category": "市", "pref": "兵庫県"},
	{"name": "加西", "category": "市", "pref": "兵庫県"},
	{"name": "加東", "category": "市", "pref": "兵庫県"},
	{"name": "三田", "category": "市", "pref": "兵庫県"},
	{"name": "三木", "category": "市", "pref": "兵庫県"},
	{"name": "小野", "category": "市", "pref": "兵庫県"},
	{"name": "西宮", "category": "市", "pref": "兵庫県"},
	{"name": "川西", "category": "市", "pref": "兵庫県"},
	{"name": "丹波", "category": "市", "pref": "兵庫県"},
	{"name": "豊岡", "category": "市", "pref": "兵庫県"},
	{"name": "加古川", "category": "市", "pref": "兵庫県"},
	{"name": "市川", "category": "町", "pref": "兵庫県"},
	{"name": "神河", "category": "町", "pref": "兵庫県"},
	{"name": "福崎", "category": "町", "pref": "兵庫県"},
	{"name": "奈良", "category": "市", "pref": "奈良県", "kento":true},
	{"name": "大和高田", "category": "市", "pref": "奈良県"},
	{"name": "下市", "category": "町", "pref": "奈良県"},
	{"name": "吉野", "category": "町", "pref": "奈良県"},
	{"name": "高取", "category": "町", "pref": "奈良県"},
	{"name": "三郷", "category": "町", "pref": "奈良県"},
	{"name": "川西", "category": "町", "pref": "奈良県"},
	{"name": "田原本", "category": "町", "pref": "奈良県"},
	{"name": "川上", "category": "村", "pref": "奈良県"},
	{"name": "十津川", "category": "村", "pref": "奈良県"},
	{"name": "下北山", "category": "村", "pref": "奈良県"},
	{"name": "上北山", "category": "村", "pref": "奈良県"},
	{"name": "東吉野", "category": "村", "pref": "奈良県"},
	{"name": "海南", "category": "市", "pref": "和歌山県"},
	{"name": "新宮", "category": "市", "pref": "和歌山県"},
	{"name": "広川", "category": "町", "pref": "和歌山県"},
	{"name": "高野", "category": "町", "pref": "和歌山県"},
	{"name": "日高", "category": "町", "pref": "和歌山県"},
	{"name": "白浜", "category": "町", "pref": "和歌山県"},
	{"name": "美浜", "category": "町", "pref": "和歌山県"},
	{"name": "日高川", "category": "町", "pref": "和歌山県"},
	{"name": "上富田", "category": "町", "pref": "和歌山県"},
	{"name": "北山", "category": "村", "pref": "和歌山県"},
	{"name": "倉吉", "category": "市", "pref": "鳥取県"},
	{"name": "米子", "category": "市", "pref": "鳥取県"},
	{"name": "岩美", "category": "町", "pref": "鳥取県"},
	{"name": "江府", "category": "町", "pref": "鳥取県"},
	{"name": "大山", "category": "町", "pref": "鳥取県"},
	{"name": "南部", "category": "町", "pref": "鳥取県"},
	{"name": "日南", "category": "町", "pref": "鳥取県"},
	{"name": "日野", "category": "町", "pref": "鳥取県"},
	{"name": "日吉津", "category": "村", "pref": "鳥取県"},
	{"name": "松江", "category": "市", "pref": "島根県", "kento":true},
	{"name": "江津", "category": "市", "pref": "島根県"},
	{"name": "大田", "category": "市", "pref": "島根県"},
	{"name": "浜田", "category": "市", "pref": "島根県"},
	{"name": "海士", "category": "町", "pref": "島根県", "ritou":true},
	{"name": "吉賀", "category": "町", "pref": "島根県"},
	{"name": "川本", "category": "町", "pref": "島根県"},
	{"name": "飯南", "category": "町", "pref": "島根県"},
	{"name": "美鄉", "category": "町", "pref": "島根県"},
	{"name": "津和野", "category": "町", "pref": "島根県"},
	{"name": "岡山", "category": "市", "pref": "岡山県", "seirei":true, "kento":true},
	{"name": "井原", "category": "市", "pref": "岡山県"},
	{"name": "玉野", "category": "市", "pref": "岡山県"},
	{"name": "新見", "category": "市", "pref": "岡山県"},
	{"name": "津山", "category": "市", "pref": "岡山県"},
	{"name": "瀬戸内", "category": "市", "pref": "岡山県"},
	{"name": "里庄", "category": "町", "pref": "岡山県"},
	{"name": "久米南", "category": "町", "pref": "岡山県"},
	{"name": "新庄", "category": "村", "pref": "岡山県"},
	{"name": "広島", "category": "市", "pref": "広島県", "seirei":true, "kento":true},
	{"name": "三原", "category": "市", "pref": "広島県"},
	{"name": "庄原", "category": "市", "pref": "広島県"},
	{"name": "府中", "category": "市", "pref": "広島県"},
	{"name": "福山", "category": "市", "pref": "広島県"},
	{"name": "江田島", "category": "市", "pref": "広島県", "ritou":true},
	{"name": "東広島", "category": "市", "pref": "広島県"},
	{"name": "坂", "category": "町", "pref": "広島県"},
	{"name": "熊野", "category": "町", "pref": "広島県"},
	{"name": "海田", "category": "町", "pref": "広島県"},
	{"name": "府中", "category": "町", "pref": "広島県"},
	{"name": "北広島", "category": "町", "pref": "広島県"},
	{"name": "大崎上島", "category": "町", "pref": "広島県", "ritou":true},
	{"name": "神石高原", "category": "町", "pref": "広島県"},
	{"name": "山口", "category": "市", "pref": "山口県", "kento":true},
	{"name": "下関", "category": "市", "pref": "山口県"},
	{"name": "宇部", "category": "市", "pref": "山口県"},
	{"name": "下松", "category": "市", "pref": "山口県"},
	{"name": "岩国", "category": "市", "pref": "山口県"},
	{"name": "上関", "category": "町", "pref": "山口県", "ritou":true},
	{"name": "平生", "category": "町", "pref": "山口県"},
	{"name": "和木", "category": "町", "pref": "山口県"},
	{"name": "阿南", "category": "市", "pref": "徳島県"},
	{"name": "阿波", "category": "市", "pref": "徳島県"},
	{"name": "吉野川", "category": "市", "pref": "徳島県"},
	{"name": "小松島", "category": "市", "pref": "徳島県"},
	{"name": "神山", "category": "町", "pref": "徳島県"},
	{"name": "石井", "category": "町", "pref": "徳島県"},
	{"name": "美波", "category": "町", "pref": "徳島県"},
	{"name": "北島", "category": "町", "pref": "徳島県"},
	{"name": "高松", "category": "市", "pref": "香川県", "kento":true},
	{"name": "三豊", "category": "市", "pref": "香川県"},
	{"name": "三木", "category": "町", "pref": "香川県"},
	{"name": "土庄", "category": "町", "pref": "香川県", "ritou":true},
	{"name": "宇多津", "category": "町", "pref": "香川県"},
	{"name": "松山", "category": "市", "pref": "愛媛県", "kento":true},
	{"name": "宇和島", "category": "市", "pref": "愛媛県"},
	{"name": "上島", "category": "町", "pref": "愛媛県", "ritou":true},
	{"name": "松前", "category": "町", "pref": "愛媛県"},
	{"name": "松野", "category": "町", "pref": "愛媛県"},
	{"name": "内子", "category": "町", "pref": "愛媛県"},
	{"name": "高知", "category": "市", "pref": "高知県", "kento":true},
	{"name": "須崎", "category": "市", "pref": "高知県"},
	{"name": "土佐", "category": "市", "pref": "高知県"},
	{"name": "南国", "category": "市", "pref": "高知県"},
	{"name": "土佐清水", "category": "市", "pref": "高知県"},
	{"name": "安田", "category": "町", "pref": "高知県"},
	{"name": "越知", "category": "町", "pref": "高知県"},
	{"name": "佐川", "category": "町", "pref": "高知県"},
	{"name": "大豊", "category": "町", "pref": "高知県"},
	{"name": "津野", "category": "町", "pref": "高知県"},
	{"name": "田野", "category": "町", "pref": "高知県"},
	{"name": "土佐", "category": "町", "pref": "高知県"},
	{"name": "本山", "category": "町", "pref": "高知県"},
	{"name": "中土佐", "category": "町", "pref": "高知県"},
	{"name": "三原", "category": "村", "pref": "高知県"},
	{"name": "大川", "category": "村", "pref": "高知県"},
	{"name": "日高", "category": "村", "pref": "高知県"},
	{"name": "北川", "category": "村", "pref": "高知県"},
	{"name": "福岡", "category": "市", "pref": "福岡県", "seirei":true, "kento":true},
	{"name": "古賀", "category": "市", "pref": "福岡県"},
	{"name": "大川", "category": "市", "pref": "福岡県"},
	{"name": "田川", "category": "市", "pref": "福岡県"},
	{"name": "福津", "category": "市", "pref": "福岡県"},
	{"name": "豊前", "category": "市", "pref": "福岡県"},
	{"name": "大野城", "category": "市", "pref": "福岡県"},
	{"name": "宇美", "category": "町", "pref": "福岡県"},
	{"name": "吉富", "category": "町", "pref": "福岡県"},
	{"name": "久山", "category": "町", "pref": "福岡県"},
	{"name": "広川", "category": "町", "pref": "福岡県"},
	{"name": "新宮", "category": "町", "pref": "福岡県"},
	{"name": "川崎", "category": "町", "pref": "福岡県"},
	{"name": "大木", "category": "町", "pref": "福岡県"},
	{"name": "佐賀", "category": "市", "pref": "佐賀県", "kento":true},
	{"name": "鹿島", "category": "市", "pref": "佐賀県"},
	{"name": "小城", "category": "市", "pref": "佐賀県"},
	{"name": "多久", "category": "市", "pref": "佐賀県"},
	{"name": "江北", "category": "町", "pref": "佐賀県"},
	{"name": "白石", "category": "町", "pref": "佐賀県"},
	{"name": "長崎", "category": "市", "pref": "長崎県", "kento":true},
	{"name": "五島", "category": "市", "pref": "長崎県", "ritou":true},
	{"name": "平戸", "category": "市", "pref": "長崎県", "ritou":true},
	{"name": "松浦", "category": "市", "pref": "長崎県"},
	{"name": "西海", "category": "市", "pref": "長崎県"},
	{"name": "大村", "category": "市", "pref": "長崎県"},
	{"name": "島原", "category": "市", "pref": "長崎県"},
	{"name": "南島原", "category": "市", "pref": "長崎県"},
	{"name": "波佐見", "category": "町", "pref": "長崎県"},
	{"name": "新上五島", "category": "町", "pref": "長崎県", "ritou":true},
	{"name": "熊本", "category": "市", "pref": "熊本県", "seirei":true, "kento":true},
	{"name": "宇城", "category": "市", "pref": "熊本県"},
	{"name": "宇土", "category": "市", "pref": "熊本県"},
	{"name": "玉名", "category": "市", "pref": "熊本県"},
	{"name": "山鹿", "category": "市", "pref": "熊本県"},
	{"name": "南関", "category": "町", "pref": "熊本県"},
	{"name": "玉東", "category": "町", "pref": "熊本県"},
	{"name": "山都", "category": "町", "pref": "熊本県"},
	{"name": "小国", "category": "町", "pref": "熊本県"},
	{"name": "大津", "category": "町", "pref": "熊本県"},
	{"name": "美里", "category": "町", "pref": "熊本県"},
	{"name": "和水", "category": "町", "pref": "熊本県"},
	{"name": "南小国", "category": "町", "pref": "熊本県"},
	{"name": "多良木", "category": "町", "pref": "熊本県"},
	{"name": "津奈木", "category": "町", "pref": "熊本県"},
	{"name": "五木", "category": "村", "pref": "熊本県"},
	{"name": "山江", "category": "村", "pref": "熊本県"},
	{"name": "水上", "category": "村", "pref": "熊本県"},
	{"name": "西原", "category": "村", "pref": "熊本県"},
	{"name": "宇佐", "category": "市", "pref": "大分県"},
	{"name": "国東", "category": "市", "pref": "大分県"},
	{"name": "中津", "category": "市", "pref": "大分県"},
	{"name": "日田", "category": "市", "pref": "大分県"},
	{"name": "別府", "category": "市", "pref": "大分県"},
	{"name": "津久見", "category": "市", "pref": "大分県"},
	{"name": "宮崎", "category": "市", "pref": "宮崎県", "kento":true},
	{"name": "西都", "category": "市", "pref": "宮崎県"},
	{"name": "都城", "category": "市", "pref": "宮崎県"},
	{"name": "日南", "category": "市", "pref": "宮崎県"},
	{"name": "高原", "category": "町", "pref": "宮崎県"},
	{"name": "国富", "category": "町", "pref": "宮崎県"},
	{"name": "新富", "category": "町", "pref": "宮崎県"},
	{"name": "川南", "category": "町", "pref": "宮崎県"},
	{"name": "美郷", "category": "町", "pref": "宮崎県"},
	{"name": "木城", "category": "町", "pref": "宮崎県"},
	{"name": "西米良", "category": "村", "pref": "宮崎県"},
	{"name": "伊佐", "category": "市", "pref": "鹿児島県"},
	{"name": "鹿屋", "category": "市", "pref": "鹿児島県"},
	{"name": "阿久根", "category": "市", "pref": "鹿児島県"},
	{"name": "知名", "category": "町", "pref": "鹿児島県", "ritou":true},
	{"name": "長島", "category": "町", "pref": "鹿児島県", "ritou":true},
	{"name": "大崎", "category": "町", "pref": "鹿児島県"},
	{"name": "屋久島", "category": "町", "pref": "鹿児島県", "ritou":true},
	{"name": "瀬戸内", "category": "町", "pref": "鹿児島県", "ritou":true},
	{"name": "三島", "category": "村", "pref": "鹿児島県", "ritou":true},
	{"name": "十島", "category": "村", "pref": "鹿児島県", "ritou":true},
	{"name": "大和", "category": "村", "pref": "鹿児島県", "ritou":true},
	{"name": "南城", "category": "市", "pref": "沖縄県"},
	{"name": "宮古島", "category": "市", "pref": "沖縄県", "ritou":true},
	{"name": "豊見城", "category": "市", "pref": "沖縄県"},
	{"name": "西原", "category": "町", "pref": "沖縄県"},
	{"name": "北谷", "category": "町", "pref": "沖縄県"},
	{"name": "本部", "category": "町", "pref": "沖縄県"},
	{"name": "久米島", "category": "町", "pref": "沖縄県", "ritou":true},
	{"name": "東", "category": "村", "pref": "沖縄県"},
	{"name": "伊江", "category": "村", "pref": "沖縄県", "ritou":true},
	{"name": "中城", "category": "村", "pref": "沖縄県"},
	{"name": "伊平屋", "category": "村", "pref": "沖縄県"},
	{"name": "南大東", "category": "村", "pref": "沖縄県", "ritou":true},
	{"name": "北大東", "category": "村", "pref": "沖縄県", "ritou":true},
	{"name": "北中城", "category": "村", "pref": "沖縄県"}
];

const DORA = {
	"川": ["川", "崎"],
	"大": ["大", "阪"],
	"島": ["島", "田"],
	"山": ["山", "口"],
	"野": ["野", "田"],
	"田": ["田", "原"],
	"南": ["南", "国"],
	"津": ["津", "山"],
	"東": ["東", "大", "阪"],
	"上": ["上", "越"],
	"小": ["小", "田", "原"],
	"松": ["松", "山"],
	"富": ["富", "山"],
	"原": ["原"],
	"高": ["高", "松"],
	"北": ["北", "見"],
	"中": ["中", "津"],
	"三": ["三", "島"],
	"美": ["美", "幌"],
	"西": ["西", "宮"],
	"城": ["城", "里"],
	"長": ["長", "崎"],
	"平": ["平", "戸"],
	"戸": ["戸", "田"],
	"豊": ["豊", "田"],
	"佐": ["佐", "賀"],
	"日": ["日", "立"],
	"井": ["井", "原"],
	"浜": ["浜", "松"],
	"岡": ["岡", "山"],
	"内": ["内", "子"],
	"木": ["木", "津", "川"],
	"吉": ["吉", "川"],
	"和": ["和", "泉"],
	"本": ["本", "庄"],
	"新": ["新", "宮"],
	"宮": ["宮", "崎"],
	"江": ["江", "別"],
	"白": ["白", "河"],
	"士": ["士", "別"],
	"泉": ["泉", "佐", "野"],
	"河": ["河", "内", "長", "野"],
	"古": ["古", "河"],
	"久": ["久", "米", "島"],
	"海": ["海", "南"],
	"下": ["下", "関"],
	"浦": ["浦", "安"],
	"坂": ["坂", "戸"],
	"里": ["里", "庄"],
	"国": ["国", "立"],
	"越": ["越", "谷"],
	"福": ["福", "岡"],
	"伊": ["伊", "賀"],
	"神": ["神", "戸"],
	"知": ["知", "立"],
	"玉": ["玉", "名"],
	"清": ["清", "須"],
	"庄": ["庄", "原"],
	"多": ["多", "賀", "城"],
	"広": ["広", "島"],
	"石": ["石", "岡"],
	"岩": ["岩", "国"],
	"加": ["加", "古", "川"],
	"宇": ["宇", "都", "宮"],
	"村": ["村", "上"],
	"根": ["根", "羽"],
	"水": ["水", "戸"],
	"鹿": ["鹿", "屋"],
	"幌": ["幌", "加", "内"],
	"阿": ["阿", "南"],
	"土": ["土", "浦"],
	"米": ["米", "子"],
	"生": ["生", "坂"],
	"波": ["波", "佐", "見"],
	"市": ["市", "川"],
	"熊": ["熊", "本"],
	"別": ["別", "府"],
	"安": ["安", "城"],
	"沼": ["沼", "津"],
	"府": ["府", "中"],
	"須": ["須", "賀", "川"],
	"屋": ["屋", "久", "島"],
	"五": ["五", "島"],
	"瀬": ["瀬", "戸"],
	"関": ["関"],
	"丹": ["丹", "波"],
	"羽": ["羽", "島"],
	"飯": ["飯", "田"],
	"取": ["取", "手"],
	"横": ["横", "浜"],
	"金": ["金", "沢"],
	"都": ["都", "城"],
	"名": ["名", "古", "屋"],
	"立": ["立", "川"],
	"十": ["十", "和", "田"],
	"会": ["会", "津", "坂", "下"],
	"奈": ["奈", "良"],
	"京": ["京", "都"],
	"阪": ["阪", "南"],
	"八": ["八", "戸"],
	"倉": ["倉", "吉"]
};
